AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  imgtggrimages:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::422245094113:role/service-role/imgtggr-images-role-9bxxbhqq'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /imgtggr-images
            Method: ANY
