/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:24cf5bb2-c513-461b-98dd-1720c988ab03",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_vq8vo23qF",
    "aws_user_pools_web_client_id": "2i36ak12rju7tk4ctvmjj306rp",
    "oauth": {},
    "aws_user_files_s3_bucket": "imgtggrqueueimages125908-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_cloud_logic_custom": [
        {
            "name": "queue",
            "endpoint": "https://gjj8yxit3d.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
